# Stage 1: Build Stage
FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Stage 2: Production Stage
FROM node:18-alpine

WORKDIR /app

# Copy only the necessary files from build stage
COPY --from=build /app /app

EXPOSE 3000

CMD ["node", "index.js"]
