apiVersion: v1
kind: Service
metadata:
  name: nodeapi-service
spec:
  type: NodePort
  selector:
    app: nodeapi
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080  # exposed on host
