apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapi
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
        - name: nodeapi
          image: jainchirag/nodeapi:v36
          ports:
            - containerPort: 3000
